name: Test Jekyll
description: Test copy of a jekyll repository
url: 'https://git-backend.github.io'
baseurl: '/test-jekyll'
email: test-jekyll@example.com
twitter: '@test-jekyll'
facebook: 'https://www.facebook.com/test-jekyll'
google_analytics: 'UA-00000000-1'
paginate:  5
gems:
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
